config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :categories
  resources :comments
  resources :boards

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get '/users/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    get '/users/sign_up', to: 'devise/registrations#new', as: :new_user_registration
    get '/users/edit', to: 'devise/registrations#edit', as: :edit_user_registration
    patch '/users', to: 'devise/registrations#update', as: :user_registration
    put '/users', to: 'devise/registrations#update', as: nil
    delete '/users', to: 'devise/registrations#delete', as: nil
    post '/users/sign_up', to: 'devise/registrations#create', as: :post_user_registration
  end

  get 'search/index'
  post 'search/search'
  get 'pages/show'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :comments
  has_many :users, through: :comments
  has_many :category_settings
  has_many :categories, through: :category_settings
  validates :title, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_required, only: [:index]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all.order(id: "DESC").page(params[:page]).per(5)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @comment = Comment.new
    @category_settings = @board.category_settings
  end

  # GET /boards/new
  def new
    @board = Board.new
    @categories = Category.all
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @categories = Category.all

    if categories_params[:categories]
      categories_params[:categories].each do |category_id|
        @category_setting = CategorySetting.new
        @category_setting.board = @board
        @category_setting.category = Category.find(category_id)
        @category_setting.save
      end
    end

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'スレッドが作成されました' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'スレッドが更新されました' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'スレッドが削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title)
    end

    def categories_params
      params.require(:board).permit(categories: [])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h3 class="header">スレッド一覧</h3>
<div class="section scrollspy">
  <table>
    <thead>
      <tr>
        <th>タイトル</th>
      </tr>
    </thead>

    <tbody>
      <% @boards.each do |board| %>
        <tr>
          <td><%= link_to board.title, board %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @boards %>
</div>

<div class="section scrollspy right-align">
  <%= link_to new_board_path, class: 'waves-effect waves-light btn' do%>
    <i class="material-icons right">add_circle</i>
    <span>新規スレッド</span>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="row">
  <div class="col xl8 offset-xl2 l8 offset-l2 m12 s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">新規スレッド作成</span>
        <% if @board.errors.any? %>
          <p>タイトルが未入力です。</p>
        <% end %>

        <%= form_for @board do |f| %>
          <div class="section scrollspy">
            <div class="input-field">
              <%= f.label :title, "タイトル" %><br />
              <%= f.text_field :title %>
            </div>
          </div>

          <span>カテゴリ</span>
          <div class="section scrollspy row">
            <% @categories.each do |category| %>
              <div class="col s3">
                <%= f.label "categories" + "_" + category.id.to_s do %>
                  <%= f.check_box(:categories, { multiple: true, checked: category[:checked], disabled: category[:disabled], include_hidden: false }, category.id ) %>
                  <span><%= category.name %></span>
                <% end %>
              </div>
            <% end %>
          </div>

          <div class="section scrollspy">
            <%= link_to new_category_path, class: 'waves-effect waves-light btn' do %>
            <i class="material-icons right">add_circle</i>
            <span>新規カテゴリ作成</span>
            <% end %>
          </div>

          <div class="section scrollspy">
            <div class="input-field right-align">
              <%= button_tag class: 'btn waves-effect waves-light' do %>
                <%= content_tag :i, "send", class: "material-icons right" %>
                スレッド作成
              <% end %>
            </div>
          </div>
        <% end %>

        <%= link_to :back, class: 'waves-effect waves-light btn' do %>
        <i class="material-icons left">arrow_back</i>
        <span>戻る</span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<h3 class="header"><%= @board.title %></h3>
<div class="section scrollspy">
  <table>
    <thead>
      <tr>
        <th>カテゴリ</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @category_settings.each do |category_setting| %>
        <tr>
          <td><%= category_setting.category.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="section scrollspy">
  <table>
    <thead>
      <tr>
        <th>レス</th>
      </tr>
    </thead>

    <tbody>
      <% @board.comments.each_with_index do |comment, i| %>
        <tr>
          <td>  
            <%= i + 1 %> : <%= comment.user.email%> : <%= simple_time(comment.created_at)%>
            <p><%= comment.content %></p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

  <% if @board.errors.any? %>
    <p>本文が未入力です。</p>
  <% end %>
<div class="section scrollspy">
  <%= form_for @comment do |f| %>
  <p>新規レス:</p>
  <div class="input-field">
    <p><%= f.text_area :content, :rows => 5 %></p>
  </div>
  <%= button_tag type: "submit", class: "right btn waves-effect waves-light" do %>
    <i class="material-icons right">send</i>
    投稿する
  <% end %>
  <%= f.hidden_field :board_id, value: @board.id %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>



  <%= link_to :back, class: 'waves-effect waves-light btn' do %>
    <i class="material-icons left">arrow_back</i>
    <span>戻る</span>
    <% end %>
  </div>