config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :categories
  resources :comments
  resources :boards

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    get '/users/cancel', to: 'devise/registrations#cancel', as: :cancel_user_registration
    get '/users/sign_up', to: 'devise/registrations#new', as: :new_user_registration
    get '/users/edit', to: 'devise/registrations#edit', as: :edit_user_registration
    patch '/users', to: 'devise/registrations#update', as: :user_registration
    put '/users', to: 'devise/registrations#update', as: nil
    delete '/users', to: 'devise/registrations#delete', as: nil
    post '/users/sign_up', to: 'devise/registrations#create', as: :post_user_registration
  end

  get 'search/index'
  post 'search/search'
  get 'pages/show'

  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(elems, {});
      });

      document.addEventListener('turbolinks:load', function() {
        elem = document.querySelector('#sidenav');
        instance = new M.Sidenav(elem, {});
      });
      document.addEventListener('turbolinks:before-visit', function() {
        elem = document.querySelector('#sidenav');
        instance = M.Sidenav.getInstance(elem);
        if (instance){
          instance.destroy();
        }
      });
    </script>
  </head>

  <body>
    <header>
      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo"><%= image_tag 'logo_877_h64.png' %></a>
          <a href="#" data-target="sidenav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
            <li><%= link_to 'スレッド一覧', boards_path %></li>
            <li><%= link_to '検索', search_index_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
      <ul class="sidenav" id="sidenav">
        <% if user_signed_in? %>
        <li><%= link_to 'スレッド一覧', boards_path %></li>
        <li><%= link_to '検索', search_index_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
        <% end %>
      </ul>
    </header>
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </main>

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">877chan.</h5>
            <p class="grey-text text-lighten-4">お問い合わせはyusanu02@gmail.comまで</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container center">
        ©2020 Yutaro Sanuki
        </div>
      </div>
    </footer>
  </body>
</html>